export * from './database.interface';
export * from './user.interface';
export * from './jwt.interface';
export * from './token.interface';
export * from './auth.interface'
export * from './otp.interface'
export * from './doctor.interface'
export * from './tag.interface'
export * from './post.interface'
export * from './react.interface'
export * from './appointment.interface'
export * from './session.interface'
export * from './review.interface'
export * from './savedPosts.interface'
export * from './cloudinary.interface'
export * from './message.interface'
export * from './measurement.interface'